
name = "DashVtk"
uuid = "1b08a953-4be3-4667-9a23-4fdd99ec3e46"
authors = ["Kitware Inc <sebastien.jourdain@kitware.com> and Plotly Technologies <xinghan@plot.ly>"]
version = "0.0.7"

[deps]
Dash = "1b08a953-4be3-4667-9a23-3db579824955"

[compact]
julia = "1.2"
Dash = ">=0.1"
